version: '3.3'
networks:
  inside-tesk-task-network:
services:
  inside-test-task:
    image: "marukhan/inside_test_task"
    networks:
      - inside-tesk-task-network
    ports:
      - "7777:7777"
  postgres:
    image: "postgres"
    networks:
      - inside-tesk-task-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
